---indent
vim.o.tabstop=4
vim.o.shiftwidth=0
vim.o.smartindent=true
vim.o.cindent=true
vim.o.expandtab=true
vim.o.indentexpr='v.lua:require"nvim-treesitter".indentexpr()'
---warp
vim.o.linebreak=true
vim.o.showbreak='↳ '
vim.o.breakindent=true
---fold
vim.o.foldmethod='expr'
vim.o.foldenable=false
vim.o.foldexpr='v:lua.vim.treesitter.foldexpr()'
---window/split
vim.o.splitbelow=true
vim.o.splitright=true
vim.o.winminheight=0
vim.o.winminwidth=0
---visual
vim.o.fillchars='vert: ,eob: ,horiz: ,horizup: ,horizdown: ,vertleft: ,vertright: ,verthoriz: '
vim.o.list=true
--vim.o.cursorline=true
vim.o.showmode=false
vim.o.statusline=' '
vim.o.ruler=false
vim.o.showcmd=false
vim.o.signcolumn='no'
vim.o.laststatus=0
vim.o.cmdheight=0
vim.o.conceallevel=2
vim.o.pumblend=20
---search
vim.o.ignorecase=true
vim.o.smartcase=true
---data
vim.o.undofile=true
vim.o.swapfile=false
---autocomplete
vim.o.completeopt='menu,menuone,popup,noselect,fuzzy'
vim.o.complete='.'
vim.o.wildmode='longest:full,full'
---other
vim.o.scrolloff=5
vim.o.timeoutlen=500
vim.o.spelloptions='camel'
vim.o.shortmess='ascoOAFWI'
vim.o.virtualedit='block,onemore'
vim.o.smoothscroll=true
vim.o.mouse='a'
vim.o.concealcursor='nc'
vim.o.shada="'500,/9,:50,<50,@9,s10"
