local sts=require'syntax-tree-surfer'
vim.keymap.set('n','vx','<cmd>STSSelectMasterNode\r',{noremap=true,silent=true})
vim.keymap.set('n','vn','<cmd>STSSelectCurrentNode\r',{noremap=true,silent=true})
vim.keymap.set('x','<C-j>','mode()=="<C-v>"?"<Plug>GoVSMDown":"<cmd>STSSelectNextSiblingNode\r"',{noremap=true,silent=true,expr=true})
vim.keymap.set('x','<C-k>','mode()=="<C-v>"?"<Plug>GoVSMUp":"<cmd>STSSelectPrevSiblingNode\r"',{noremap=true,silent=true,expr=true})
vim.keymap.set('x','<C-h>','mode()=="<C-v>"?"<Plug>GoVSMLeft":"<cmd>STSSelectParentNode\r"',{noremap=true,silent=true,expr=true})
vim.keymap.set('x','<C-l>','mode()=="<C-v>"?"<Plug>GoVSMRight":"<cmd>STSSelectChildNode\r"',{noremap=true,silent=true,expr=true})
vim.keymap.set('x','<C-S-j>','mode()=="<C-v>"?"<Plug>GoVSDDown":"<cmd>STSSwapNextVisual\r"',{noremap=true,silent=true,expr=true})
vim.keymap.set('x','<C-S-k>','mode()=="<C-v>"?"<Plug>GoVSDUp":"<cmd>STSSwapPrevVisual\r"',{noremap=true,silent=true,expr=true})
vim.keymap.set('x','<C-S-h>','mode()=="<C-v>"?"<Plug>GoVSDLeft": ":m 0\rgv"',{noremap=true,silent=true,expr=true})
vim.keymap.set('x','<C-S-l>','mode()=="<C-v>"?"<Plug>GoVSDRight":":m $\rgv"',{noremap=true,silent=true,expr=true})
vim.keymap.set('x','<A-k>','<Plug>GoVMLineUp',{noremap=true,silent=true})
vim.keymap.set('x','<A-j>','<Plug>GoVMLineDown',{noremap=true,silent=true})
vim.keymap.set('n','<A-k>','<Plug>GoNMLineUp',{noremap=true,silent=true})
vim.keymap.set('n','<A-j>','<Plug>GoNMLineDown',{noremap=true,silent=true})
vim.keymap.set('x','<A-S-k>','<Plug>GoVDLineUp',{noremap=true,silent=true})
vim.keymap.set('x','<A-S-j>','<Plug>GoVDLineDown',{noremap=true,silent=true})
vim.keymap.set('n','<A-S-k>','<Plug>GoNDLineUp',{noremap=true,silent=true})
vim.keymap.set('n','<A-S-j>','<Plug>GoNDLineDown',{noremap=true,silent=true})
vim.keymap.set('n','<C-S-o>',':lua require("syntax-tree-surfer").go_to_top_node_and_execute_commands(false,{"normal!O","normal!O","startinsert"})\r',{noremap=true,silent=true})
vim.keymap.set('n','gFu',function() sts.targeted_jump({'function','arrrow_function','function_definition'}) end,{noremap=true,silent=true})
vim.keymap.set('n','gFe',function() sts.targeted_jump({'if_statement','else_clause','else_statement','elseif_statement'}) end,{noremap=true,silent=true})
vim.keymap.set('n','gFo',function() sts.targeted_jump({'for_statement','while_statement','switch_statement'}) end,{noremap=true,silent=true})
vim.keymap.set('n','gFv',function() sts.targeted_jump({'variable_declaration'}) end,{noremap=true,silent=true})
vim.keymap.set('n','gFs',function() sts.targeted_jump({'string'}) end,{noremap=true,silent=true})
vim.keymap.set('n','gFi',function() sts.targeted_jump({'ineger'}) end,{noremap=true,silent=true})
vim.keymap.set('n','gFa',function() sts.targeted_jump({"function","if_statement","else_clause","else_statement",
    "elseif_statement","for_statement","while_statement","switch_statement",}) end,{noremap=true,silent=true})
vim.keymap.set('n','<A-N>',function() sts.filtered_jump('default',true) end,{noremap=true,silent=true})
vim.keymap.set('n','<A-P>',function() sts.filtered_jump('default',false) end,{noremap=true,silent=true})
