vim.g.neo_tree_remove_legacy_commands=1
require'neo-tree'.setup{
    use_default_mappings=false,
    close_if_last_window=true,
    open_files_in_last_window=true,
    sort_case_insensitive=true,
    source_selector={winbar=true},
    default_component_configs={
        indent={
            indent_size=1,
            padding=0,
            last_indent_marker='│',
        },
        icon={
            folder_closed='',
            folder_open='',
            folder_empty='',
            default='',
        },
        name={trailing_slash=true},
    },
    window={
        mappings={
            ['<cr>']='open',
            l='open',
            h='close_node',
            t='open_tabnew',
            S='open_split',
            s='open_vsplit',
            z='close_all_nodes',
            Z='expand_all_nodes',
            R='refresh',
            a='add',
            A='add_directory',
            D='delete',
            r='rename',
            y='copy_to_clipboard',
            d='cut_to_clipboard',
            p='paste_from_clipboard',
            c='copy',
            m='move',
            q='close_window',
            ['?']='show_help',
            ['<']='prev_source',
            ['>']='next_source',
        },
    },
    filesystem={
        window={
            mappings={
                H='toggle_hidden',
                f='filter_on_submit',
                ['<C-x>']='clear_filter',
                ['<bs>']='navigate_up',
                ['.']='set_root',
                ['[g']='prev_git_modified',
                [']g']='next_git_modified',
            }
        },
        filtered_items={visible=true},
        follow_current_file=true,
    },
    buffers={
        window={
            mappings={
                ['<bs>']='navigate_up',
                ['.']='set_root',
                ['D']='buffer_delete',
            },
        },
    },
    git_status={
        window={
            mappings={
                A='git_add_all',
                gu='git_unstage_file',
                ga='git_add_file',
                gr='git_revert_file',
                gc='git_commit',
                gp='git_push',
                gg='git_commit_and_push',
            },
        },
    },
}
