local telescope=require'telescope'

telescope.load_extension'luasnip'
telescope.load_extension'harpoon'
telescope.load_extension'notify'
telescope.load_extension'attempt'
telescope.load_extension'vim_bookmarks'
telescope.load_extension'refactoring'
telescope.load_extension'changed_files'
telescope.load_extension'project'
telescope.load_extension'fzf'
telescope.load_extension'conventional_commits'
telescope.load_extension'gh'
telescope.load_extension'live_grep_args'
telescope.load_extension'packer'
telescope.load_extension'ui-select'
telescope.load_extension'gitmoji'
telescope.load_extension'tele_tabby'
telescope.load_extension'file_browser'
telescope.load_extension'asynctasks'
