require'nvim-treesitter.configs'.setup({ensure_installed={
    'python','lua','fish',
    'bash','vim',
    --
    'go','c','html','c_sharp',
    'java','javascript','css',
    'cpp','rust','typescript',
    'haskell',
    --
    'help','org','markdown',
    'json','toml','hjson',
    'jsonc','norg','jsdoc',
    'json5','rst','todotxt',
    --
    'comment','regex','query',
},rainbow={enable=true},
highlight={enable=true},
pairs={enable=true,highlight_pair_events={'CursorMoved'}},
textsubjects={enable=true,
    prev_selection='Q',
    keymaps={
        ['a,']='textsubjects-smart',
        ['a.']='textsubjects-container-outer',
        ['i.']='textsubjects-container-inner',
}},
context_commentstring={enable=true},
})
require'orgmode'.setup_ts_grammar()
--refactor={smart_rename={keymaps={smart_rename="gr"}}},
--vim.keymap.set('n','gr':TSEnable refactor.smart_rename<cr>gr')
