vim.cmd.iabbrev'<buffer> re return'
vim.cmd.iabbrev'<buffer> ree return end'
vim.cmd.iabbrev'<buffer> l local'
vim.cmd.iabbrev'<buffer> fu function'
vim.cmd.iabbrev'<buffer> fum function M'
vim.cmd.iabbrev'<buffer> vpp vim.pprint'
vim.cmd.iabbrev'<buffer> vpt vim.traceback'
vim.cmd.iabbrev'<buffer> vl vim.lg'
