vim.cmd.iabbrev'<buffer> l local'
vim.cmd.iabbrev'<buffer> fu function'
vim.cmd.iabbrev'<buffer> vpp vim.pprint'
vim.cmd.iabbrev'<buffer> vpt vim.traceback'
vim.cmd.iabbrev'<buffer> vpo vim.oprint'
vim.cmd.iabbrev'<buffer> vpa vim.aprint'
